(clear)
(load "F:/IBM chaf watson/IBMCW-master/ontologia.clp")
(load "F:/IBM chaf watson/IBMCW-master/recetas.clp")
(load "F:/IBM chaf watson/IBMCW-master/reglas.clp")
(reset)
(progn (dribble-on "dribble.txt") (run) (dribble-off))
